# config.yaml — wird 1:1 in ENV gemappt

features:
  backend: disk
  device: cuda
  use_mask: true
  max_kp: 25000
  debug_every: 20

  lg:
    detection_threshold: 0.0001
    nms: 2
    resize: 1536
    remove_borders: 2
    force_num: true

  preproc:
    clahe: true
    clahe_clip: 4.0
    clahe_tiles: 16
    unsharp: true
    unsharp_sigma: 1.0
    unsharp_amount: 1.3
    noise: false
    noise_std: 1.5
    mask_dilate: 6

matching:
  backend: lightglue
  features: disk
  ratio: 0.82
  depth_confidence: -1
  width_confidence: -1
  filter_threshold: 0.09

masking:
  enable: true
  method: rembg
  overwrite_images: false
  params:
    alpha_thr: 0.4
    save_debug: true

sfm:
  init_ratio: 0.5
  init_max_span: 8
  densify: true
  use_keyframes: true
  use_loops: true
  pose_smoothing: true
  smooth_lambda: 0.01

mvs:
  enable: true
  mode: "single"
  params:
    device: cuda
    scale: 1.0

    # ---- Frame-Auswahl (bucketed) ----
    ref_strategy: "bucket"   # "bucket" | "bestk" | "step"
    ref_topk: 36             # Anzahl der gewünschten points_ref_XXXX
    ref_min_gap: 3           # Sicherheitsabstand (nur für "bestk")
    ref_step: 3              # nur für "step"

    # ---- Seeds & Fill ----
    seed_radius: 2
    seed_min: 200
    seed_sample: 200000
    beta: 4.0
    fill_iters: 150
    mask_pad: 6

    # ---- Output ----
    export_mesh: false       # <- wir bauen KEIN dense_mesh hier
    poisson_depth: 10

fusion:
  enable: true
  num_refs: 36               # 18–24 ist ein guter Sweet-Spot; 119 lohnt selten
  mode: "majority"           # "any" | "majority" | "all"
  min_in_mask: 2
  use_depth: true
  depth_tol: 0.03
  voxel: 0.0                 # 0 = auto
  sdf_tau_rel: 0.010         # Soft-Sparse Leitplanke (1% BB-Diagonale)
  sdf_tau: 0.0               # 0 = aus
  export_mesh: true
  poisson_depth: 10
  chunk: 400000

  # NEW: Silhouette-Fill
  fill:
    enable: true
    stride: 2                # größer -> weniger Punkte, schneller
    inpaint: true            # fülle Löcher in depth_XXXX.npy per cv.inpaint
    inpaint_radius: 3
    max_per_view: 150000     # Sicherheitslimit pro View
