# config.yaml  — Buddha: maximal dicht & löcherfrei

# Feature extraction
features:
  backend: superpoint          # robust & dicht; DISK/ALIKED optional testbar
  device: cuda
  use_mask: true               # nur Statue matchen, weniger False-Matches im BG
  max_kp: 20000                # viele Keypoints für lückenlose Flächen
  debug_every: 20

  # LightGlue/learned extractor tuning
  lg:
    detection_threshold: 0.0003  # niedriger => mehr (auch schwächere) Punkte
    nms: 2                       # dichter beieinanderliegende Punkte zulassen
    resize: 1280                 # moderat; kein unnötiges Upscaling
    remove_borders: 2            # Kanten nicht hart abschneiden
    force_num: true              # versucht max_kp zu erreichen

  # Optionales Gray-Preprocessing (wirkt nur auf Detektion)
  preproc:
    clahe: true
    clahe_clip: 4.0              # starke, aber noch stabile Kontrastanhebung
    clahe_tiles: 8               # lokale Anpassung gut für Details
    unsharp: true                # Kanten leicht betonen (feine Reliefs)
    unsharp_sigma: 1.0
    unsharp_amount: 1.3
    noise: false                 # kein Dithering – Stabilität vor Zufall
    noise_std: 1.5
    mask_dilate: 6               # Maske etwas erweitern, um Randlöcher zu vermeiden

  # SIFT-Fallback / -Explizit
  sift:
    contrast: 0.004
    edge: 12
    sigma: 1.2

# Masking / Preprocessing
masking:
  enable: true
  method: rembg                  # robuste Objektmaske ohne Alphahalo
  overwrite_images: false
  params:
    # rembg (nur falls umgestellt):
    alpha_thr: 0.4
    save_debug: true
    # sam2:
    keep: largest                # größtes Segment = Statue

# Matching
matching:
  backend: lightglue
  features: superpoint          # konsistent zum Extractor
  ratio: 0.82                    # nur BF-Fallback; bei LG wirkungslos
  depth_confidence: -1           # Early-Stop AUS → volle Tiefe (max Genauigkeit)
  width_confidence: -1           # Pruning AUS → volle Breite (mehr Matches)
  filter_threshold: 0.06         # niedriger => mehr Matches, RANSAC räumt auf

# SfM
sfm:
  init_ratio: 0.5
  init_max_span: 8
  densify: true
  use_keyframes: false
  use_loops: true
  pose_smoothing: true
  smooth_lambda: 0.01
