# Feature extraction
features:
  backend: disk
  device: cuda
  use_mask: true
  max_kp: 10000
  debug_every: 30

# Masking / Preprocessing
masking:
  enable: true
  method: rembg            # rembg | sam2
  overwrite_images: false
  params:
    # rembg:
    alpha_thr: 0.1
    save_debug: true
    # sam2:
    keep: largest          # largest | best_score

# Matching
matching:
  backend: lightglue
  features: disk
  ratio: 0.82

# SfM
sfm:
  init_ratio: 0.3
  init_max_span: 4
  densify: true
  use_keyframes: true
  use_loops: true
  pose_smoothing: true
  smooth_lambda: 0.001
