# config.yaml

# Feature extraction
features:
  backend: superpoint          # superpoint | disk | aliked | sift
  device: cuda
  use_mask: true
  max_kp: 12000
  debug_every: 30

  # LightGlue/learned extractor tuning
  lg:
    detection_threshold: 0.0008   # kleiner => mehr Keypoints
    nms: 2                        # kleiner => dichter
    resize: 1024                  # längere Bildkante fürs Netz
    remove_borders: 2
    force_num: true               # versucht max_num_keypoints zu erzwingen

  # Optionales Gray-Preprocessing (wirkt nur auf Detektion, nicht auf Originalbilder)
  preproc:
    clahe: true
    clahe_clip: 3.0
    clahe_tiles: 8
    unsharp: true
    unsharp_sigma: 1.0
    unsharp_amount: 1.5
    noise: true
    noise_std: 1.5
    mask_dilate: 8                # für Masken-Kanten; 5–8 ist gut

  # SIFT-Fallback / -Explizit
  sift:
    contrast: 0.004
    edge: 12
    sigma: 1.2

# Masking / Preprocessing
masking:
  enable: true
  method: rembg            # rembg | sam2
  overwrite_images: false
  params:
    # rembg:
    alpha_thr: 0.1
    save_debug: true
    # sam2:
    keep: largest          # largest | best_score

# Matching
matching:
  backend: lightglue
  features: superpoint          # superpoint | disk | aliked | sift
  ratio: 0.82

# SfM
sfm:
  init_ratio: 0.3
  init_max_span: 4
  densify: true
  use_keyframes: true
  use_loops: true
  pose_smoothing: true
  smooth_lambda: 0.001