

# Feature extraction
features:
  backend: aliked          # superpoint | sift | disk | aliked
  device: cuda                 # cuda | cpu (must match the matching device)
  use_mask: false
  max_kp: 12000
  debug_every: 30              # 0 = off; e.g., 30 saves every 30th mask

# Matching
matching:
  backend: lightglue           # lightglue | classic
  ratio: 0.82                  # only for classic SNN; ignored by lightglue

# SfM
sfm:
  init_ratio: 0.3              # fraction of neighbors for initial pair (0..1)
  init_max_span: 4             # max frame distance for the start pair
  densify: true
  use_keyframes: true
  use_loops: true
  pose_smoothing: true
  smooth_lambda: 0.001
