

lowlight:
  enable: true
  weights: "/home/joelnanai/PycharmProjects/Mobile_Robotik/3D_Model_Creation_from_Video/Zero-DCE_extension/Zero-DCE++/snapshots_Zero_DCE++/Epoch99.pth"
  pattern: "*.png"
  scale_factor: 1

features:
  backend: disk
  device: cuda
  use_mask: true
  max_kp: 25000
  debug_every: 5

  lg:
    detection_threshold: 0.0000045
    nms: 3
    resize: 1024
    remove_borders: 2
    force_num: true

  preproc:
    clahe: true
    clahe_clip: 4.0
    clahe_tiles: 16
    unsharp: true
    unsharp_sigma: 1.0
    unsharp_amount: 1.3
    noise: false
    noise_std: 1.5
    mask_dilate: 5

  fill:
    enable: true
    thr: 0.08
    kp_radius: 4
    erode: 2
    dilate: 6
    merge_r: 3
    gamma: 0.5
    clahe_clip: 8.0
    clahe_tiles: 24
    unsharp_sigma: 1.0
    unsharp_amount: 1.5
    noise: true
    noise_std: 1.4

matching:
  backend: lightglue
  features: disk
  ratio: 0.82
  depth_confidence: -1
  width_confidence: -1
  filter_threshold: 0.07
  retr_enable: true
  retr_k: 8192
  retr_sample_per_img: 6000
  retr_topk: 48
  retr_min_sim: 0.05
  neighbor_span: 10

masking:
  enable: true
  method: rembg
  overwrite_images: false
  params:
    alpha_thr: 0.18
    save_debug: true

sfm:
  init_ratio: 0.5
  init_max_span: 8
  densify: true
  use_keyframes: true
  use_loops: true
  pose_smoothing: true
  smooth_lambda: 0.01

mvs:
  enable: true
  mode: "single"
  params:
    device: cuda
    scale: 1.0

    ref_strategy: "bestk"
    ref_topk: 60
    ref_min_gap: 3
    ref_step: 2

    seed_radius: 2
    seed_min: 200
    seed_sample: 200000
    beta: 4.0
    fill_iters: 200
    mask_pad: 6

    gap_fill_enable: true
    fill_max_gap: 10
    fill_depth_std: 0.03
    fill_depth_rel: 0.06
    fill_stride: 1

    fill_max_points: 4000000
    voxel_after_fill: 0.0015

carve:
  enable: true
  use_all_masks: false
  views: 32
  tau: 0.50
  mask_dilate: 2

texturing:
  enable: true
  mode: "auto"
  divisor: 12
  weight_power: 2.0
  use_masks: true
  mask_dilate: 2
  backfill: "nearest"
  in_ply: fused_points.ply
  out_ply: fused_textured_points.ply

mesh:
  downsample: 1
  voxel_size: 0.0
  outlier_nb: 20
  outlier_std: 1.6

surface_close:
  enable: false
  poisson_depth: -1
  poisson_scale: 1.1
  target_points: 800000


carve_pre_sparse: true
carve_pre_views: 32
carve_pre_tau: 0.5
carve_pre_dilate: 2
mvs_keep_all_sparse: true