# config.yaml — Werte werden 1:1 in ENV gemappt

features:
  backend: disk
  device: cuda
  use_mask: true
  max_kp: 25000
  debug_every: 20

  lg:
    detection_threshold: 0.0001
    nms: 2
    resize: 1536
    remove_borders: 2
    force_num: true

  preproc:
    clahe: true
    clahe_clip: 4.0
    clahe_tiles: 16
    unsharp: true
    unsharp_sigma: 1.0
    unsharp_amount: 1.3
    noise: false
    noise_std: 1.5
    mask_dilate: 6

  sift:
    contrast: 0.004
    edge: 12
    sigma: 1.2

masking:
  enable: true
  method: rembg
  overwrite_images: false
  params:
    alpha_thr: 0.4
    save_debug: true

matching:
  backend: lightglue
  features: disk
  ratio: 0.82
  depth_confidence: -1
  width_confidence: -1
  filter_threshold: 0.09

sfm:
  init_ratio: 0.5
  init_max_span: 8
  densify: true
  use_keyframes: true
  use_loops: true
  pose_smoothing: true
  smooth_lambda: 0.01

mvs:
  enable: true
  mode: "all"
  params:
    device: cuda
    scale: 0.60          # etwas größer hilft Details
    max_views: 20        # zu viele Quellen schaden (Occlusions)
    n_planes: 192        # dichteres Z-Sampling
    depth_expand: 0.12   # etwas breiterer Bereich vermeidet Clipping
    patch: 5             # kleinere Fenster = schärfere Kanten
    cost_thr: 0.48
    min_valid_frac: 0.01
    poisson_depth: 11

    torch_dtype: float32
    src_batch: 2
    depth_chunk: 24

    depth_sampling: inverse
    depth_default: "0.30,1.60"    # besserer Fallback für Statue
    depth_percentiles: [10, 90]   # robust gegen Ausreißer im sparse
    mask_pad: 4                   # weniger Nachbarschaft
    strict_masks: true
    pctl_ktail: 3                 # etwas strenger

    # NEU – wird als ENV gesetzt:
    photo_margin: 0.04            # MVS_PHOTO_MARGIN
    min_support: 4                # MVS_MIN_SUPPORT

    export_mesh: true
