# config.yaml — wird 1:1 in ENV gemappt

features:
  backend: disk
  device: cuda
  use_mask: true
  max_kp: 25000
  debug_every: 20

  lg:
    detection_threshold: 0.0001
    nms: 2
    resize: 1536
    remove_borders: 2
    force_num: true

  preproc:
    clahe: true
    clahe_clip: 4.0
    clahe_tiles: 16
    unsharp: true
    unsharp_sigma: 1.0
    unsharp_amount: 1.3
    noise: false
    noise_std: 1.5
    mask_dilate: 6

  sift:
    contrast: 0.004
    edge: 12
    sigma: 1.2

masking:
  enable: true
  method: rembg
  overwrite_images: false
  params:
    alpha_thr: 0.4
    save_debug: true

matching:
  backend: lightglue
  features: disk
  ratio: 0.82
  depth_confidence: -1
  width_confidence: -1
  filter_threshold: 0.09

sfm:
  init_ratio: 0.5
  init_max_span: 8
  densify: true
  use_keyframes: true
  use_loops: true
  pose_smoothing: true
  smooth_lambda: 0.01

mvs:
  enable: true
  mode: "single"
  params:
    device: cuda
    scale: 1.0

    # ---- Frame-Auswahl (bucketed) ----
    ref_strategy: "bucket"   # "bucket" | "bestk" | "step" | "auto"
    ref_topk: 6              # Anzahl der Buckets = Anzahl gewünschter Posen
    ref_min_gap: 1           # Sicherheitsabstand in Indizes (für bestk)
    ref_step: 3              # nur für strategy=step

    # ---- Seeds & Fill ----
    seed_radius: 2
    seed_min: 200
    seed_sample: 200000
    beta: 4.0
    fill_iters: 150
    mask_pad: 6

    # ---- Output ----
    export_mesh: true
    poisson_depth: 10

fusion:
  enable: true
  mode: "majority"     # "any" | "majority" | "all"
  min_in_mask: 2       # optional, z.B. >=2 Masken müssen den Punkt „sehen“
  use_depth: true      # zusätzlich Depth-Konsistenz nutzen (falls depth/*.npy vorhanden)
  depth_tol: 0.03      # akzeptiere z <= depth + tol
  export_mesh: true
  poisson_depth: 10
  chunk: 400000